codecov:
  branch: release

coverage:
  precision: 1
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.1%
        branches: null

    patch:
      default:
        target: auto
        threshold: 0.1%
        branches: null

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  branches: null
  behavior: default
