name: Verify pip-installability

on: [workflow_dispatch]

jobs:
  deploy:
    name: Verify pip-installability
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set branch name as env variable
      run: |
        echo Current branch: ${GITHUB_REF#refs/heads/}
        echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Install only using pip
      run:
        pip install git+https://github.com/PMEAL/OpenPNM.git@${BRANCH_NAME}

    - name: Test the installation
      run:
        python -c "import openpnm"
